services:
  java:
    build: ./docker/java
    container_name: java
    ports:
      - 8081:8080
    tty: true
    # 実行可能jarが生成される箇所のみマウント
    volumes:
      - ./spring/build/libs:/jar
    working_dir: /jar
    networks:
      - my-network
    depends_on:
      - postgres

  postgres:
    build: ./docker/postgres
    ports:
      - 5433:5432
    container_name: postgres
    networks:
      - my-network
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db

networks:
  my-network:

  # react:
  #   build: ./docker/react
  #   container_name: react
  #   ports:
  #     - 5174:5173
  #   volumes:
  #     - ./spring/react:/src
  #   stdin_open: true
