FROM php:8.3.9-fpm

# 必要なパッケージのインストールとDocker PHP Extensionsのインストール
RUN apt-get update && apt-get upgrade -y && \
  apt-get install -y zip unzip git curl && \
  docker-php-ext-install pdo_mysql && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Composerのインストール
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# composerで入れたパッケージ用にパス通す
ENV PATH="$PATH:/var/www/une-app/vendor/bin"
ENV PATH="$PATH:/var/www/deux-app/vendor/bin"

# Node.jsのインストール
RUN curl -sL https://deb.nodesource.com/setup_22.x | bash - 
RUN apt-get install -y nodejs
